import './globals.css'
import { Bellefair } from '@next/font/google';

import NavBar from '../components/NavBar';
import BgContainer from '../components/BgContainer';

const bellefair = Bellefair({
  weight: "400",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className={bellefair.className}>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width,initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <NavBar />
        <BgContainer>
          {children}
        </BgContainer>
      </body>
    </html>
  )
}
