import './globals.css'
import { Bellefair } from '@next/font/google';

import Navbar from '../components/Navbar';

const bellefair = Bellefair({
  weight: "400",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className={bellefair.className}>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  )
}
